### ISSUE TITLE
PanelSwWixExtension4 File Cross Contamination Issue

### ISSUE THREAD

**Issue by DSmitj** [nirbar/PanelSwWixExtension#11]
I was going through checking files from my WiX3 install to my WiX4 install.  It appears that the file harvest is pulling files of the same name from different directories and putting them in the current directory that it is harvesting files from.  I'm talking about files like web.config and index.html to name a couple.

I'm seeing this behavior in multiple installs.  Some installs are pulling a lot of files and others are not.

Is there a way to try the harvest of one directory at a time to see if doing it that way eliminates the problem?

Thanks,
D

**Comment by nirbar** [comment]
@DSmitj Can you zip and attach the folder you're harvesting, the folder after installing the MSI, and the heat command line?

**Comment by DSmitj** [comment]
@nirbar I'll try to get permission to release the code but it probably isn't going to happen.

It happens in multiple installs where it is a certain file in each install but never the same file in multiple installs, i.e. index.html and web.config.  This is from a small install that pulls in two web applications.

By the cmd-line I assume it is what I'm using in the WiXproj file:
  <PropertyGroup>
    <HarvestOutOneDirectory>$(HarvestOutOneDirectory)</HarvestOutOneDirectory>
    <HarvestOutTwoDirectory>$(HarvestOutTwoDirectory)</HarvestOutTwoDirectory>
  </PropertyGroup>
  <PropertyGroup>
    <HarvestFileSuppressUniqueIds>false</HarvestFileSuppressUniqueIds>
    <HarvestFileGenerateGuidsNow>true</HarvestFileGenerateGuidsNow>
    <HarvestDirectorySuppressCom>true</HarvestDirectorySuppressCom>
    <HarvestDirectorySuppressRegistry>true</HarvestDirectorySuppressRegistry>
    <HarvestDirectorySuppressRootDirectory>true</HarvestDirectorySuppressRootDirectory>
  </PropertyGroup>
  <PropertyGroup>
    <HarvestDirectoryAdditionalOptions>-ext "$(PanelSwWixHarvestExtension)" -exc "*.pdb;*.md;*.Development.json;*.not-used.json;*.dll.config;*.snk;*.mdb;App.config;web.config"</HarvestDirectoryAdditionalOptions>
  </PropertyGroup>
  <ItemGroup>
    <HarvestDirectory Include="$(HarvestOutTwoDirectory)\Web1\Product1.Web1">
      <ComponentGroupName>ProductOne_WebOne_Components</ComponentGroupName>
      <DirectoryRefId>PRODUCT_WEBONE_FOLDER</DirectoryRefId>
    </HarvestDirectory>
    <BindPath Include="$(HarvestOutTwoDirectory)\Web1\Product1.Web1" />
  </ItemGroup>
  <ItemGroup>
    <HarvestDirectory Include="$(HarvestOutTwoDirectory)\Web2\Product2.Web2">
      <ComponentGroupName>ProductTwo_WebTwo_Components</ComponentGroupName>
      <DirectoryRefId>PRODUCT_WEBTWO_FOLDER</DirectoryRefId>
    </HarvestDirectory>
    <BindPath Include="$(HarvestOutTwoDirectory)\Web2\Product2.Web2" />
  </ItemGroup>

For this particular install the harvest is pulling in the index.html from Product2 Web2 and placing it in the deployment folder for Product1 Web1.

Like I said it varies from install to install.  I've seen the wrong file be a web.config file among others.  It is always the same file for each install no matter how many times that I compile the project.  It's really weird.

**Comment by nirbar** [comment]
@DSmitj I don't need the code, just a something to reproduce with, such as zip of files to harvest and the heat command line.

I'm getting confused - does the issue occur with a single msi for which harvesting creates a mess with the files?
Or does it happen when installing multiple msi packages that mess up each other's files?

**Comment by DSmitj** [comment]
@nirbar Sorry for the confusion.

It happens in multiple installs.  For example, InstallA.msi may pull the index.html file from WebApplicationOne and put it in the directory for WebApplicationTwo even though it is being told to put it in the WebApplicationOne directory.  It does this every time the install's wixproj is built, the file never changes to a different file.  It doesn't seem to be a random which makes it even more weird.

Like wise, InstallB.msi takes a web.config file from a published project and puts it in the directory other than the directory that it is being told to put it in.  Once again the file doesn't change every time that the wixproj is built.  It is always the web.config file.

What do you need for the heat command line?  I'm just using propertygroups and itemsgroups in the wixproj per your suggestion when I asked about this on the WiX4 area.

Is there a way to turn on logging to see what is going in your code?  It just seems to run, create wxs files plus text files with some info but nothing else.

Is there a way to get your code to harvest each directory in a serial manner to see if that eliminates the problem?  I was thinking it may be getting confused if it is running multiple threads at the same time.

I'll work on getting you a generic install that duplicates the issue.

**Comment by nirbar** [comment]
@DSmitj From your description it doesn't seem related to the extension.
Try removing the `-ext "$(PanelSwWixHarvestExtension)" -exc ".pdb;.md;.Development.json;.not-used.json;.dll.config;.snk;*.mdb;App.config;web.config"` part, and see if the problem persists.
If so, then the issue might be some sort of mess in your project files

**Comment by DSmitj** [comment]
@nirbar I commented out the additional parameters and the file is still the wrong file.

I'm still going through the install code and the actual code to make it generic.  There are a lot of finger prints to remove.

Honestly, the project file is pretty generic so I didn't think it would do anything since the bulk of the project deals with the harvest.

**Comment by nirbar** [comment]
@DSmitj If you're getting the wrong file regardless of the additional parameters then the extension isn't related to the issue you're experiencing.
You can contact me on my website panel-sw.com if you want to help with it

**Comment by DSmitj** [comment]
@nirbar Thanks and sorry I wasted your time.

I just found the doco for Heat.  Not sure why I didn't find it before.
