### ISSUE TITLE
Reading Json file from Project TargetDir

### ISSUE THREAD

**Issue by Elencon** [nirbar/PanelSwWixExtension#4]
Shalom

I created sample test project with Product file:

<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:PanelSW="http://schemas.panel-sw.co.il/wix/WixExtension" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
  <Product Id="{769C11E5-D811-4CE3-BE79-CC23725E6B38}" Name="$(var.ProjectName)" Language="1033" Version="1.0.0.0" Manufacturer="Eneriqs Ltd" UpgradeCode="{8DC7207F-59B4-45E6-90B0-75769F8040B8}">
    <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />

    <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />
    <MediaTemplate />

    <Property Id='JSON_CUSTOMER_ID'>
      <PanelSW:JsonJpathSearch JPath="$.id" FilePath="$(var.ProjectDir)Configuration.json"/>
    </Property>

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        <Directory Id="INSTALLFOLDER" Name="UnitTestSetup">
        </Directory>
      </Directory>
    </Directory>

  </Product>
</Wix>

My Configuration.json file is:

{
	"id": 8
}

When I execute "Install" it creates proper records in log
Excerpt from Log:

SFXCA: Binding to CLR version v4.0.30319
Calling custom action PswManagedCA!PswManagedCA.JsonJPath.JsonJpathSearch
Initialized from PswManagedCA v2.31.3.0
Running Expression '$.id' on 'C:\MyDev\installer\ZipFileUT\ZipFileUT\Configuration.json'
MSI (c) (7C!48) [22:51:08:022]: PROPERTY CHANGE: Adding JSON_CUSTOMER_ID property. Its value is '8'.
Action ended 22:51:08: JsonJpathSearch. Return value 1.
Which is correct.

If i put  Configuration.json in the same directory with msi file and set 
PanelSW:JsonJpathSearch JPath="$.id" FilePath="Configuration.json"/> i get;

Excerpt from Log:
SFXCA: Binding to CLR version v4.0.30319
Calling custom action PswManagedCA!PswManagedCA.JsonJPath.JsonJpathSearch
Initialized from PswManagedCA v2.31.3.0
Running Expression '$.id' on 'Configuration.json'
File not found: 'Configuration.json'

So it looks like this extension can not find file in directory of msi file. I need to manipulate 
Configuration.json file in the folder of msi, as in my second variant. Is it possible and how?

**Comment by nirbar** [comment]
@Elencon This isn't related to the extension, Windows Installer doesn't work with relative paths. You must supply the full absolute path to Configuration.json
You can use DirectorySearch and FileSearch to resolve the full path.

**Comment by Elencon** [comment]
Get it. Thank you.
