### ISSUE TITLE
Multiple DeletePath Custom actions

### ISSUE THREAD

**Issue by Elencon** [nirbar/PanelSwWixExtension#5]
Shalom
I
1) need to copy tmp.zip file to INSTALLFOLDER1
2) Unzip it in this folder 
3) Delete Tmp.zip in  INSTALLFOLDER1
I'm doing it with following text and everything works perfectly
Then i  want to add Delete INSTALLFOLDER1 on uninstall, I do this by uncommenting two lines:
1)  
  <Property Id="MSIFASTINSTALL" Value="1" />
 

  <PanelSW:Unzip Id="_1" TargetFolder="[INSTALLFOLDER1]" ZipFile="[INSTALLFOLDER1]Tmp.zip" OverwriteMode="Unmodified"><![CDATA[Not Installed]]></PanelSW:Unzip>
  <PanelSW:DeletePath Id="DELETE_TMP_ZIP" Path="[INSTALLFOLDER1]Tmp.zip"><![CDATA[Not Installed]]></PanelSW:DeletePath>

  <InstallExecuteSequence>
    <Custom Action="UnzipSched" Before="InstallFinalize" >NOT Installed</Custom>
    <Custom Action="DeletePath" After="UnzipSched" >NOT Installed</Custom>
    

  </InstallExecuteSequence>
  </Product>

  <Fragment>
    
    
    <ComponentGroup Id="ProductComponents">

        <Component Directory="INSTALLFOLDER1" Guid="{AF91AF47-771E-4055-90AD-AF6A015C46B7}">
          <File Source="Config.txt" KeyPath="yes" Compressed="no"/>
        </Component>

        <Component Directory="INSTALLFOLDER1" Guid="{AEB0CC6D-D8E5-40BC-974E-04A7FDF52CD2}">
          <File Source="Tmp.zip" KeyPath="yes" Compressed="no"/>
        </Component>

    </ComponentGroup>
  </Fragment>
  
</Wix>

**Comment by nirbar** [comment]
Not sure I understand what you need, but...
  - Unzip has a DeleteZip attribute which you can set to yes to delete the zip file after extracting it.
  - WiX util extension has [RemoveFolderEx](https://wixtoolset.org/documentation/manual/v3/xsd/util/removefolderex.html) which you can use to recursively uninstall a folder on uninstall

**Comment by Elencon** [comment]
This is the problem of GitHub. It only shows my entire comment when I pu
[Comment.txt](https://github.com/nirbar/PanelSwWixExtension/files/6427565/Comment.txt)
[Comment.txt](https://github.com/nirbar/PanelSwWixExtension/files/6427568/Comment.txt)

sh on edit . I enclose the entire text of my issue. Thank you in advance for help

**Comment by nirbar** [comment]
You can only author DeletePath once in InstallExecuteSequence.

**Comment by Elencon** [comment]
Thank you
